### ISSUE TITLE
Fatal error: Call to undefined function assertNotEqual()

### ISSUE THREAD

**Issue by AlessandroMinoccheri** [fmalk/codeigniter-phpunit#20]
Hi,
I'm trying to use this assertion:
```
$this->assertNotEqual('', 'test');
```

but return me this error:
```
Fatal error: Call to undefined function assertNotEqual()
```

I have also tried:
```
$this->assertNotEquals('', 'test');
```

But same error.

**Comment by fmalk** [comment]
Does your test class extends `PHPUnit_Framework_TestCase`?
These are standard functions, so it should just be a problem of you calling them outside their context.

**Comment by WickedSilver** [comment]
Just for future reference:
Try using ```$this::assertNotEquals```

The assert functions are static so they should be callable using the double semicolon.
