### ISSUE TITLE
Launch only one test

### ISSUE THREAD

**Issue by AlessandroMinoccheri** [fmalk/codeigniter-phpunit#27]
Hi,
I have more tests in folder models.

If I would like to launch only the test file 09NewsTest.php how can I do that?

Thanks

**Comment by fmalk** [comment]
In CLI, you can do `phpunit folder\MyUnitTest` and that'll execute just that test.
Using XML configs, you can use the `<testsuite><file>` tags to pinpoint the file you're interested.
It's really all in https://phpunit.de/manual/current/en/organizing-tests.html#organizing-tests.xml-configuration
