### ISSUE TITLE
Fatal error: Call to a member function elapsed_time()

### ISSUE THREAD

**Issue by asakapab0i** [fmalk/codeigniter-phpunit#28]
Seems like `global $BM and $CFG;` is not working

**Comment by feryardiant** [comment]
Whats your CI version? did you've overwrite your system/core?
I've tested for both (2.x & 3.x) without any errors.

**Comment by asakapab0i** [comment]
Ahh my bad I forgot to change the constants in CodeIgniter.php.

It is fixed now.


Awesome work by the way :+1:
