### ISSUE TITLE
testing libraries

### ISSUE THREAD

**Issue by stephane-wis** [fmalk/codeigniter-phpunit#37]
Hi,
I have a Cockpit library in application/libraries.
I'm using CI 3.0.2, a little modified by adding a public folder that contains the index.php, *.js, *.css, all images and other public resources. Path in the index.php have been changed accordingly.
Test units were written for the models, and ran well until a library was added (without prefix). Running the web app is OK, running the phpunit gives an error about a missing CI_Cockpit (although the library is Cockpit). 
I tried with a prefix AQT_Cockpit, phpunit complains about a missing CI_AQT_Cockpit
I tried with a suffix Cockpit_lib, phpunit complains about a missing CI_Cockpit_lib
Finally, to continue working, I added (temporarily) at line 76 of system/core/Controller.php  
`if (is_cli() && $class != 'Cockpit')`
to escape the line 
`$this->$var =& load_class($class);`
I hate to do this, but this can help you resolving/finding the problem.

**Comment by feryardiant** [comment]
AFAIK, `load_class($class)` will only find [prefixed](https://github.com/bcit-ci/CodeIgniter/blob/3.0-stable/system/core/Common.php#L155-L179) classes. If you want to load your own lib or model that not prefixed, just go with `this->load->class('cockpit`)`

**Comment by fmalk** [comment]
@feryardiant his class seems to be prefixed by CI_
Does your CLI command has arguments? I've had problems using CLI arguments from phpunit on specific controllers

**Comment by stephane-wis** [comment]
No arguments, just running `phpunit` on the command line

**Comment by stephane-wis** [comment]
I do not prefix my classes and the `load_class($class)` is CodeIgniter Framework code.
If I prefix the library e.g. MY_Cockpit then the Framework loads CI_MY_Cockpit.
This happens only when I run the `phpunit`, and never with I run the code from a browser.

**Comment by feryardiant** [comment]
@stephane-wis `load_class($class)` is use for internal CI system level only, not for application level.

**Comment by feryardiant** [comment]
But, about
```
This happens only when I run the phpunit, and never with I run the code from a browser.
```
I've also had this problem with CI but in different cases.

**Comment by stephane-wis** [comment]
I do not use load_class($class), the Framework does.

**Comment by feryardiant** [comment]
Ah, sorry @stephane-wis I miss these line

> Finally, to continue working, I added (temporarily) at line 76 of system/core/Controller.php

> `if (is_cli() && $class != 'Cockpit')`
> to escape the line 
> `$this->$var =& load_class($class);`

**Comment by stephane-wis** [comment]
fmalk: did you succeed to reproduce the problem?

**Comment by fmalk** [comment]
@stephane-wis no, and I tried

**Comment by cnadig-cc** [comment]
@stephane-wis What alternative did you use to avoid the problem of libraries being prefixed with CI_ ?

**Comment by stephane-wis** [comment]
Hi Chai Nadig,I dropped the idea of using fmalk phpunit and found a way to use the phpunit of sebastian.On 30 Apr 2016, at 04:54, Chai Nadig <notifications@github.com> wrote:@stephane-wis What alternative did you use to avoid the problem of libraries being prefixed with CI_ ?—You are receiving this because you were mentioned.Reply to this email directly or view it on GitHub

**Comment by stephane-wis** [comment]
Hi Chai Nadig.
In packagist I have found : kenjis/ci-phpunit-test 
I'm using that one for now without problem. Sorry to have given you a too short answer 12 days ago. For the moment I have some more time to give you a more complete answer. 
Have a nice day.

**Comment by cnadig-cc** [comment]
Hi Stephane,

Thanks for getting back to me! I have switched to kenjis/ci-phpunit-test
now. It works well for me! Thanks for your time and answer.
